### ISSUE TITLE
ROS 7 support TODO list

### ISSUE THREAD

**Issue by cheretbe** [cheretbe/packer-routeros#4]
* [x] convert template from JSON to HCL
* [x] change boot command sequence 
    * [x] use variables for `boot_command`  
    * [x] make admin password consistent between versions (`/user set [/user find name="admin"] password=""`) 
* [x] make disabling of packages in `setup.rsc` conditional (`:put [:pick [/system package update get installed-version] 0 1]`) 
* [x] ~~try to use checksums (https://github.com/cheretbe/notes/blob/master/mitmproxy.md)~~
